// <auto-generated />
namespace Gallery.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Added_new_UserPathImages_field_in_TemporaryMedia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_new_UserPathImages_field_in_TemporaryMedia));
        
        string IMigrationMetadata.Id
        {
            get { return "202006121329172_Added_new_UserPathImages_field_in_TemporaryMedia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
