// <auto-generated />
namespace Gallery.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Added_field_Name_and_isDeleted_in_Media : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_field_Name_and_isDeleted_in_Media));
        
        string IMigrationMetadata.Id
        {
            get { return "202005221555317_Added_field_Name_and_isDeleted_in_Media"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
